### ISSUE TITLE
setup sentry

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-google-action#11]
- [x] https://docs.sentry.io/clients/node/
- [x] https://firebase.google.com/docs/functions/config-env use to pass config of sentry and the rest services
- [x] user's context https://docs.sentry.io/clients/node/#adding-context
- [x] app's context https://docs.sentry.io/clients/node/#breadcrumbs

**Comment by alkesh47** [comment]
I know this project is included for GSOC 2018, is there any contributor's guide that I should go through or should I jump right in? Also is there any dedicated chat forum or IRC for this project?

**Comment by savannahar68** [comment]
@hyzhak  @bimlendra  @juliascript 
Hello sir, im getting following error while running the project locally, seems there some firebase issue, it would be helpful of you ,if you guide me for getting started so that I can contribute
I have set up everything
Have **nodejs, npm and express** installed
also ran **npm install** in functions folder
Created a project on firebase with proper name and added to project by **firebase use --add** (and selected project name)
When i run this command - **DEBUG=ia:* npm start** it gives me this error

error : 
![image](https://user-images.githubusercontent.com/20986069/37381907-d3601b9e-2765-11e8-9ffc-275e5b5ef0e0.png)
Please help

**Comment by hyzhak** [comment]
Hello @savannahar68! If you issue is not related to `Sentry setup` could you create a separate issue for it and we would try to help you there?

**Comment by savannahar68** [comment]
Greetings sir,
I have created a new issue, please can you help with that so that we can
contribute to the project
