### ISSUE TITLE
Prepare support of Alexa platform

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-google-action#142]
- [x] compare features of Google Actions and Alexa platform [here](https://github.com/internetarchive/internet-archive-google-action/wiki/Google-Action-v.-Alexa)
- [x] examples for open source project, which use both platforms and work with music or podcasts (don't have wiki page yet)

# Important features
- user's session state
- simple chatting with a user
- suggestings
- support of [ssml](https://developers.google.com/actions/reference/ssml)
- audio playing and its control
- endpoint

**Comment by TheDreamSaver** [comment]
Hi I would like to make an Alexa skill for Internet Archive. Can I do that as part of GSoC? I am fairly new to open source but have quite an experience creating Alexa skills.

**Comment by TheDreamSaver** [comment]
So should I start building the Alexa skill as soon as possible? 
Or should I fill in a proposal for GSoC mentioning the Alexa Skill.

P.S. This is my first time tinkering with GSoC/Open Source, so have little idea how that works or how I can contribute to any org in general as well. That's why asking the above questions.
